// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Used by the Prisma CLI (migrate, studio, etc.) — must be Supabase's
    // direct connection (port 5432), not the pooled one, since the pooler
    // doesn't support the prepared statements migrations need.
    url: process.env["DIRECT_URL"],
  },
});
