export type FeatureSeed = { label: string; value?: string; included: boolean };
export type TranslationSeed = { locale: string; name: string; tagline: string; features: FeatureSeed[] };
export type PlanSeed = {
  key: string;
  sortOrder: number;
  popular: boolean;
  originalPrice: number;
  price: number;
  translations: TranslationSeed[];
};

// Mirrors content/locales/{id,en}.ts `pricing.plans` in inchathub-frontend at
// the time this seed was written. Update both places together if pricing
// copy changes until the frontend reads plans from this API instead.
export const pricingPlans: PlanSeed[] = [
  {
    key: "starter",
    sortOrder: 0,
    popular: false,
    originalPrice: 1_500_000,
    price: 900_000,
    translations: [
      {
        locale: "id",
        name: "Starter",
        tagline: "Start awal dengan fitur chatbot siap pakai",
        features: [
          { label: "WhatsApp Official WABA", value: "1x", included: true },
          { label: "WhatsApp UnOfficial Regular", value: "1x", included: true },
          { label: "WhatsApp UnOfficial Business", value: "1x", included: true },
          { label: "Telegram Channel", value: "1x", included: true },
          { label: "Instagram Channel", value: "1x", included: true },
          { label: "FB Messenger Channel", value: "1x", included: true },
          { label: "Email Channel", value: "1x", included: true },
          { label: "Web Live Chat Channel", value: "1x", included: true },
          { label: "X Twitter Channel", included: true },
          { label: "Thread Channel", included: false },
          { label: "Microsoft Teams Channel", included: false },
          { label: "AI Agent", value: "3x", included: true },
          { label: "Chatbots Model", value: "3x", included: true },
          { label: "User Accounts", value: "3x", included: true },
          { label: "Whatsapp Templates", value: "10x", included: true },
          { label: "Storage", value: "1 GB", included: true },
          { label: "AI Response", value: "1.000x", included: true },
          { label: "Messages/Month", value: "3.000x", included: true },
          { label: "Email/Month", value: "1.000x", included: true },
          { label: "Scraping Data/Day", included: false },
          { label: "Google Sheets Integration", included: false },
          { label: "Shipping Cost Calculator", included: false },
          { label: "Custom Domain", included: false },
          { label: "24/7 Support", included: false },
        ],
      },
      {
        locale: "en",
        name: "Starter",
        tagline: "A ready-to-use chatbot to get you started",
        features: [
          { label: "WhatsApp Official WABA", value: "1x", included: true },
          { label: "WhatsApp UnOfficial Regular", value: "1x", included: true },
          { label: "WhatsApp UnOfficial Business", value: "1x", included: true },
          { label: "Telegram Channel", value: "1x", included: true },
          { label: "Instagram Channel", value: "1x", included: true },
          { label: "FB Messenger Channel", value: "1x", included: true },
          { label: "Email Channel", value: "1x", included: true },
          { label: "Web Live Chat Channel", value: "1x", included: true },
          { label: "X Twitter Channel", included: true },
          { label: "Thread Channel", included: false },
          { label: "Microsoft Teams Channel", included: false },
          { label: "AI Agent", value: "3x", included: true },
          { label: "Chatbots Model", value: "3x", included: true },
          { label: "User Accounts", value: "3x", included: true },
          { label: "Whatsapp Templates", value: "10x", included: true },
          { label: "Storage", value: "1 GB", included: true },
          { label: "AI Response", value: "1,000x", included: true },
          { label: "Messages/Month", value: "3,000x", included: true },
          { label: "Email/Month", value: "1,000x", included: true },
          { label: "Scraping Data/Day", included: false },
          { label: "Google Sheets Integration", included: false },
          { label: "Shipping Cost Calculator", included: false },
          { label: "Custom Domain", included: false },
          { label: "24/7 Support", included: false },
        ],
      },
    ],
  },
  {
    key: "pro",
    sortOrder: 1,
    popular: true,
    originalPrice: 2_600_000,
    price: 1_900_000,
    translations: [
      {
        locale: "id",
        name: "Pro",
        tagline: "Maksimalkan performa dengan fitur lebih lengkap",
        features: [
          { label: "WhatsApp Official WABA", value: "3x", included: true },
          { label: "WhatsApp UnOfficial Regular", value: "2x", included: true },
          { label: "WhatsApp UnOfficial Business", value: "2x", included: true },
          { label: "Telegram Channel", value: "2x", included: true },
          { label: "Instagram Channel", value: "1x", included: true },
          { label: "FB Messenger Channel", value: "1x", included: true },
          { label: "Email Channel", value: "1x", included: true },
          { label: "Web Live Chat Channel", value: "1x", included: true },
          { label: "X Twitter Channel", included: false },
          { label: "Thread Channel", included: false },
          { label: "Microsoft Teams Channel", included: false },
          { label: "AI Agent", value: "10x", included: true },
          { label: "Chatbots Model", value: "10x", included: true },
          { label: "User Accounts", value: "5x", included: true },
          { label: "Whatsapp Templates", value: "50x", included: true },
          { label: "Storage", value: "3 GB", included: true },
          { label: "AI Response", value: "3.000x", included: true },
          { label: "Messages/Month", value: "5.000x", included: true },
          { label: "Email/Month", value: "3.000x", included: true },
          { label: "Scraping Data/Day", included: false },
          { label: "Google Sheets Integration", included: false },
          { label: "Shipping Cost Calculator", included: false },
        ],
      },
      {
        locale: "en",
        name: "Pro",
        tagline: "Maximize performance with a fuller feature set",
        features: [
          { label: "WhatsApp Official WABA", value: "3x", included: true },
          { label: "WhatsApp UnOfficial Regular", value: "2x", included: true },
          { label: "WhatsApp UnOfficial Business", value: "2x", included: true },
          { label: "Telegram Channel", value: "2x", included: true },
          { label: "Instagram Channel", value: "1x", included: true },
          { label: "FB Messenger Channel", value: "1x", included: true },
          { label: "Email Channel", value: "1x", included: true },
          { label: "Web Live Chat Channel", value: "1x", included: true },
          { label: "X Twitter Channel", included: false },
          { label: "Thread Channel", included: false },
          { label: "Microsoft Teams Channel", included: false },
          { label: "AI Agent", value: "10x", included: true },
          { label: "Chatbots Model", value: "10x", included: true },
          { label: "User Accounts", value: "5x", included: true },
          { label: "Whatsapp Templates", value: "50x", included: true },
          { label: "Storage", value: "3 GB", included: true },
          { label: "AI Response", value: "3,000x", included: true },
          { label: "Messages/Month", value: "5,000x", included: true },
          { label: "Email/Month", value: "3,000x", included: true },
          { label: "Scraping Data/Day", included: false },
          { label: "Google Sheets Integration", included: false },
          { label: "Shipping Cost Calculator", included: false },
        ],
      },
    ],
  },
  {
    key: "business",
    sortOrder: 2,
    popular: false,
    originalPrice: 3_500_000,
    price: 2_900_000,
    translations: [
      {
        locale: "id",
        name: "Business",
        tagline: "Solusi custom dengan prioritas dukungan support",
        features: [
          { label: "WhatsApp Official WABA", value: "5x", included: true },
          { label: "WhatsApp UnOfficial Regular", value: "3x", included: true },
          { label: "WhatsApp UnOfficial Business", value: "3x", included: true },
          { label: "Telegram Channel", value: "3x", included: true },
          { label: "Instagram Channel", value: "1x", included: true },
          { label: "FB Messenger Channel", value: "1x", included: true },
          { label: "Email Channel", value: "1x", included: true },
          { label: "Web Live Chat Channel", value: "1x", included: true },
          { label: "X Twitter Channel", included: false },
          { label: "Thread Channel", included: false },
          { label: "Microsoft Teams Channel", included: false },
          { label: "AI Agent", value: "20x", included: true },
          { label: "Chatbots Model", value: "20x", included: true },
          { label: "User Accounts", value: "10x", included: true },
          { label: "Whatsapp Templates", value: "100x", included: true },
          { label: "Storage", value: "5 GB", included: true },
          { label: "AI Response", value: "10.000x", included: true },
          { label: "Messages/Month", value: "10.000x", included: true },
          { label: "Email/Month", value: "5.000x", included: true },
          { label: "Scraping Data/Day", value: "30x", included: true },
          { label: "Google Sheets Integration", included: true },
          { label: "Shipping Cost Calculator", included: true },
        ],
      },
      {
        locale: "en",
        name: "Business",
        tagline: "A custom solution with priority support",
        features: [
          { label: "WhatsApp Official WABA", value: "5x", included: true },
          { label: "WhatsApp UnOfficial Regular", value: "3x", included: true },
          { label: "WhatsApp UnOfficial Business", value: "3x", included: true },
          { label: "Telegram Channel", value: "3x", included: true },
          { label: "Instagram Channel", value: "1x", included: true },
          { label: "FB Messenger Channel", value: "1x", included: true },
          { label: "Email Channel", value: "1x", included: true },
          { label: "Web Live Chat Channel", value: "1x", included: true },
          { label: "X Twitter Channel", included: false },
          { label: "Thread Channel", included: false },
          { label: "Microsoft Teams Channel", included: false },
          { label: "AI Agent", value: "20x", included: true },
          { label: "Chatbots Model", value: "20x", included: true },
          { label: "User Accounts", value: "10x", included: true },
          { label: "Whatsapp Templates", value: "100x", included: true },
          { label: "Storage", value: "5 GB", included: true },
          { label: "AI Response", value: "10,000x", included: true },
          { label: "Messages/Month", value: "10,000x", included: true },
          { label: "Email/Month", value: "5,000x", included: true },
          { label: "Scraping Data/Day", value: "30x", included: true },
          { label: "Google Sheets Integration", included: true },
          { label: "Shipping Cost Calculator", included: true },
        ],
      },
    ],
  },
  {
    key: "enterprise",
    sortOrder: 3,
    popular: false,
    originalPrice: 5_500_000,
    price: 4_900_000,
    translations: [
      {
        locale: "id",
        name: "Enterprise",
        tagline: "Paket fleksibel plus support tim khusus untuk bisnis",
        features: [
          { label: "WhatsApp Official WABA", value: "10x", included: true },
          { label: "WhatsApp UnOfficial Regular", value: "10x", included: true },
          { label: "WhatsApp UnOfficial Business", value: "10x", included: true },
          { label: "Telegram Channel", value: "5x", included: true },
          { label: "Instagram Channel", value: "3x", included: true },
          { label: "FB Messenger Channel", value: "3x", included: true },
          { label: "Email Channel", value: "1x", included: true },
          { label: "Web Live Chat Channel", value: "1x", included: true },
          { label: "X Twitter Channel", value: "1x", included: true },
          { label: "Thread Channel", value: "1x", included: true },
          { label: "Microsoft Teams Channel", value: "1x", included: true },
          { label: "AI Agent", value: "Unlimited", included: true },
          { label: "Chatbots Model", value: "Unlimited", included: true },
          { label: "User Accounts", value: "Unlimited", included: true },
          { label: "Whatsapp Templates", value: "Unlimited", included: true },
          { label: "Storage", value: "Unlimited", included: true },
          { label: "AI Response", value: "Unlimited", included: true },
          { label: "Messages/Month", value: "Unlimited", included: true },
          { label: "Email/Month", value: "Unlimited", included: true },
          { label: "Scraping Data/Day", value: "50x", included: true },
          { label: "Google Sheets Integration", included: true },
          { label: "Shipping Cost Calculator", included: true },
        ],
      },
      {
        locale: "en",
        name: "Enterprise",
        tagline: "A flexible plan plus a dedicated support team",
        features: [
          { label: "WhatsApp Official WABA", value: "10x", included: true },
          { label: "WhatsApp UnOfficial Regular", value: "10x", included: true },
          { label: "WhatsApp UnOfficial Business", value: "10x", included: true },
          { label: "Telegram Channel", value: "5x", included: true },
          { label: "Instagram Channel", value: "3x", included: true },
          { label: "FB Messenger Channel", value: "3x", included: true },
          { label: "Email Channel", value: "1x", included: true },
          { label: "Web Live Chat Channel", value: "1x", included: true },
          { label: "X Twitter Channel", value: "1x", included: true },
          { label: "Thread Channel", value: "1x", included: true },
          { label: "Microsoft Teams Channel", value: "1x", included: true },
          { label: "AI Agent", value: "Unlimited", included: true },
          { label: "Chatbots Model", value: "Unlimited", included: true },
          { label: "User Accounts", value: "Unlimited", included: true },
          { label: "Whatsapp Templates", value: "Unlimited", included: true },
          { label: "Storage", value: "Unlimited", included: true },
          { label: "AI Response", value: "Unlimited", included: true },
          { label: "Messages/Month", value: "Unlimited", included: true },
          { label: "Email/Month", value: "Unlimited", included: true },
          { label: "Scraping Data/Day", value: "50x", included: true },
          { label: "Google Sheets Integration", included: true },
          { label: "Shipping Cost Calculator", included: true },
        ],
      },
    ],
  },
];
